name: 'Validate code'
description: 'Typecheck + ESLint + tests'
runs:
  using: 'composite'
  steps:
    - name: Run Typecheck
      run: |
        echo "Running Typecheck"
        npm run typecheck
      shell: bash

    - name: Run lint:fix
      run: |
        echo "Running ESlint"
        npm run lint:fix
      shell: bash

    - name: Run tests
      run: |
        echo "Running tests"
        npm run test
      shell: bash
